name: Scan options
on:
  workflow_dispatch:
  schedule:
    # every 3 hours
    # https://crontab.guru
    - cron: "0 */3 * * *"
jobs:
  scan-options:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Yarn install
        run: |
          yarn
      - name: yarn start
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: | # Scan options for all models of a random language
          yarn start --model *
