name: Search colors
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/every-5-minutes
    - cron: "*/5 * * * *"
jobs:
  search-colors:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Yarn install
        run: |
          yarn
      - name: setup git config
        run: |
          # setup the username and email
          git config --global user.name "Tesla Tracker"
          git config --global user.email "<>"

      - name: yarn start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: | # Scan 30 colors and wait 500 ms between each query
          yarn start --indexLength 50 --delay 500
